name: Feature request
description: Propose a new feature or enhancement
title: "[Feature]: "
labels: ["feature"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description of the feature update
      description: What feature was implemented/updated?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Alternatives considered, mockups, links, related issues.
